#
# Module manifest for module 'psDeploy'
#
# Generated by: Romain Prieto
#
# Generated on: 2/24/2010
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'psDeploy.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '02023c34-7b68-4f58-bdf2-03da2e3afb54'

# Author of this module
Author = 'Romain Prieto'

# Company or vendor of this module
CompanyName = 'ThoughtWorks'

# Copyright statement for this module
Copyright = '2010'

# Description of the functionality provided by this module
Description = 'Cmdlets for deployment automation in a Windows environment'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

}

